# ============================================================
# Versions' Name Goto https://wiki.vg/Protocol_version_numbers
# 2024.12.19 Note: Goto https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge
# Support from 16w32a to 1.21.4

# Some Versions Name Changed
# 20w14Infinity => (20w14âˆ)
# 1.14.3-Combat => (1.14.3 - Combat Test)
# ============================================================

RecommendedVersion: ['1.16.4', '1.16.5', '1.17']

# How many ticks do you want to delay
delay: 50L

# Whether to detect when the player joins the server
DetectWhenJoin: true

# If the version does not match, what to do next.
# Commands
# Messages
VersionNotMatchFunction: 'Messages'

# If Doing next is Command
# (%playerName% => Player Name)
# (%playerVersion% => Player Version)
Commands: []

# If Doing next is Message
# (%playerName% => Player Name)
# (%playerVersion% => Player Version)
Messages: []